### ISSUE TITLE
Use atexit module to redraw cursor on program exit

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/cursor#1]
README states: 

> Note that the cursor will stay hidden until you call cursor.show() — even after exiting your python script!
> An alternative is using the HiddenCursor() class in conjunction with Python's with statement. This will make sure that the cursor is shown again after running your code, even if exceptions are raised.

As another easy alternative, you might consider using the Python [atexit](https://docs.python.org/2/library/atexit.html) module (or just mentioning the possibility in the README  for that matter). Could work as follows:

``` python
>>> import cursor
>>> import atexit
>>> atexit.register(cursor.show)
<function show at 0x7f6ebbf7b668>
>>> cursor.hide()
>>> print("hello world!")
hello world!
>>> exit()
```

**Comment by GijsTimmers** [comment]
Thanks for reporting!
