### ISSUE TITLE
Allow user to choose the stream to output escape sequences

### ISSUE THREAD

**Issue by manrajgrover** [GijsTimmers/cursor#2]
Currently, escape sequences are outputted to `stdout` which is not customizable. A feature request would be to allow users to select the stream themselves.

**Comment by GijsTimmers** [comment]
I see. I will consider to write this myself when I have time but that may take a while. I will happily accept any PR's that implement this in a nice fashion.

**Comment by manrajgrover** [comment]
@GijsTimmers I'll make the necessary changes and raise a PR for it.
