### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by PatrikKopkan** [GijsTimmers/cursor#4]
Hi,
I would like to ask you if there would be possibility of relicensing this repo to MIT if would author of the answer on stackoverflow agree?

**Comment by GijsTimmers** [comment]
I am not a big fan of this idea to be honest. Can you explain to me what the issue is with the licensing as it is?

**Comment by PatrikKopkan** [comment]
It is content license, not code license. It is not compat with GPL. I want to package your project in fedora because it is dependency for pipenv and other dependencies are compat with gpl. And there is some legal issue with using stuff on stackoverflow which I dont really understand.

**Comment by GijsTimmers** [comment]
I see. I thought it was GPL already but apparently it's CC. I will
relicense to GPL asap.

Op wo 23 jan. 2019 10:13 schreef PatrikKopkan <notifications@github.com>:

**Comment by hroncok** [comment]
Note that pipenv bundles this and this being GPL will most likely block them.

**Comment by hroncok** [comment]
> It is not compat with GPL.

Is it not? Creative Commons (other than CC0 are generally [not good idea for code](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software)), but that does not make them non GPL compatible.

> Version 4.0 of CC's Attribution-ShareAlike (BY-SA) license is one-way compatible with the GNU General Public License version 3.0 (GPLv3).

(Here, it was 2.5, but that is now a detail.)

I am worried that the license was changed to a very strict copyleft license. Now if a project (such as pipenv) uses it, they would need to change their license too.

Would you please reconsider at least LGPL, if not MIT?

**Comment by GijsTimmers** [comment]
> I am worried that the license was changed to a very strict copyleft license. Now if a project (such as pipenv) uses it, they would need to change their license too.

That's right.

> Would you please reconsider at least LGPL, if not MIT?

I'm not a big fan of the licences you mentioned - I believe in free open source software and also believe its usage should be promoted. Relicensing to LGPL allows for `cursor` getting integrated in closed-source non-free software, the kind of software I try to avoid using.

It's a shame to see you guys abandoning this little piece of software but I'm confident that this is the right way forward.

**Comment by hroncok** [comment]
I see that you are aware of the consequences. I won't try to persuade you. Thanks for clarifying.
