### ISSUE TITLE
Update installing instruction in the README

### ISSUE THREAD

**Issue by goggle** [GijsTimmers/cursor#5]
I am maintaining a AUR package (https://aur.archlinux.org/packages/python-cursor/) for `cursor` since August 2018. If you think that this is done right (the package build instructions can be seen in the PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-cursor), we could mention this as the preferred way to install `cursor` for Arch Linux users. Maybe we could write somehing like this in the README:

**Arch Linux:**
The package is available in the [AUR](https://aur.archlinux.org/packages/python-cursor/). You can either use a AUR helper or manually install it:
```
git clone https://aur.archlinux.org/python-cursor.git
cd python-cursor
makepkg -si
sudo pacman -U python-cursor-x.y.z-r-any.pkg.xz
```

In addition, many people do not consider it as _good practice_ to use `sudo pip` to install python packages. It installs the python files on your system path, which is usually already maintained by the system's package manager (`pacman` for Arch users, `apt-get` for Debian/Ubuntu users). Maybe you should encourage users to set up virtual environments or at least use `pip install ---user` to install the package.

**Comment by GijsTimmers** [comment]
Thanks for taking the time to write this issue. This is actually pretty high on my to do list, so expect an update.

**Comment by GijsTimmers** [comment]
Alright I pushed an update containing your suggestions. In my testing, the line
 
    sudo pacman -U python-cursor-x.y.z-r-any.pkg.xz

was not necessary as `makepkg -si` will issue this command automatically. Can you check whether this happens on your system, too? I am considering removing that line.

**Comment by goggle** [comment]
@GijsTimmers Thats absolutely correct, it's not necessary to run `pacman -U` when you use `makepkg` with the `-i` option.
