### ISSUE TITLE
Is this code GPL-3.0-only or GPL-3.0-or-later?

### ISSUE THREAD

**Issue by duncanmmacleod** [GijsTimmers/cursor#8]
As in the subject, just wondering if this code is strictly [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html).

**Comment by GijsTimmers** [comment]
Hi,

GPL-3.0-or-later.

**Comment by duncanmmacleod** [comment]
Thanks @GijsTimmers!
